apiVersion: v1
kind: Service
metadata:
    name: "akspoccluster-c1ae"
    labels:
        app: "akspoccluster-c1ae"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "akspoccluster-c1ae"